Support multiple slates for a single Watcher config
cbsinteractive/hawkeye pull request #49
Opened 2022-01-05 16:18 UTC by LyleScott

The POST payload for creating a Watcher has changed: `slate_url` is no longer a root level field and has been moved into each `transitions` object. Each transition now has a `from_context` and `to_context` object corresponding to each `to` and `from` state value on that payload. When the `to` or `from`  is `slate`, a `slate_context` object is required in the respective `to_context`/`from_context` object. This is where `slate_url` now lives.

For example:

```json
{
  ...,
  "transitions": [
    {
      "from": "content",
      "to": "slate",
      "to_context": {
          "slate_context": {
              "slate_url": "file://./resources/foo/bar.jpg"
          }
      },
    }
  ]
}
```

An attempt at API validation was made to enforce a few things:
- URL scheme must be one of `http`, `https` when `export HAWKEYE_ENV=prod`, otherwise it accepts `http`, `https`, and `file`. 
- File extension must be one of `jpg,jpeg,png`. **I'm open for advice on what else should be listed here**
- the URL generally gets parsed by a URL parser to verify sanity
- if `to=slate` or `from=slate`, then `slate_context` must be supplied (and _that_ must have a `slate_url` value)

## Disclaimer

There's a bit of an avalanche of changes around adding comments, readmes, and test assets. Apologies for the noise, but it was hard to split them out into tiny POST dev PRs.

I'm newer to Rust, so please bare with me. :) I'm all ears for advice and getting pointers on where to look for stuff! I definitely see some things that could be better now that I have more knowledge after this feature, but it'll get taken care of since we'll be adding features to it. I could almost certainly `clone()` less now that I'm more familiar with lifetimes, for example!

TODO: I need to add a few more tests after reviewing this PR myself

2022-01-06 07:51 UTC, LyleScott commented on hawkeye-api/Cargo.toml
> +k8s-openapi = { version = "0.13.1", default-features = false, features = ["v1_22"]}
they are really working on this stuff! Slid this in  and rolled with it for some days after toubleshooting some local docker issues.

2022-01-06 07:59 UTC, LyleScott commented on hawkeye-api/src/filters.rs
> +use eyre::ErrReport;
There was an attempt at bubbling Validation errors that "bubble up". I noticed there was an issue for addressing validation API wide, but I've only implemented it for `to_context`/`from_context`/`slate_context` validations since this implementation. Partly because this is one of the first things I wrote for the multislate feature and I was a bit new to Rust, partly because I didn't want to do a bunch of work without agreeing on the approach. IN any case, I guess the plumbing here for Warp is unavoidable.

2022-01-06 08:01 UTC, LyleScott commented on hawkeye-core/Cargo.toml
> +url = "2.2.2"
use for a quick sanity check of the url. think Python urllib parse

2022-01-06 08:01 UTC, LyleScott commented on hawkeye-core/Cargo.toml
> -serde_json = "1.0"
moved to a dev dep

2022-01-06 08:02 UTC, LyleScott commented on hawkeye-core/src/config.rs
> +        .unwrap_or("jpg,jpeg,png".into())
I'm open for suggestions here 😅

2022-01-06 08:06 UTC, LyleScott commented on hawkeye-worker/Cargo.toml
> +dssim = "2.11.5"
bumping the dssim version and basically breaking matching scared me a bit, so i'm going to lock this dep down. Since 3.x is out, it'll hardly get updates I'd imagine, anyways.

2022-01-06 08:09 UTC, LyleScott commented on hawkeye-worker/src/actions.rs
> +);
This is making transitions more stateful since we can now have multiple `Transition<from=content to=slate>` transitions, now. The secondary key is now the SlateContext, which contains a `slate_url=` value and thus derives uniqueness.

2022-01-06 15:08 UTC, rafaelcaricio requested changes
First pass on reviewing. Have you ran [`cargo clippy`](https://github.com/rust-lang/rust-clippy) after the changes here?

2022-01-06 15:08 UTC, rafaelcaricio commented on hawkeye-worker/src/img_detector.rs
> +            .iter()
Maybe you want to make this parallel? https://docs.rs/rayon/latest/rayon/iter/index.html :)

2022-01-06 15:08 UTC, rafaelcaricio commented on hawkeye-worker/src/main.rs
> +    // let detector = SlateDetector::new(&slate::load_img(watcher.slate_url.as_str())?)?;
Maybe delete this commented code?

2022-01-06 15:57 UTC, jakubclark reviewed
Looks good overall, just a couple minor comments

2022-01-06 15:57 UTC, jakubclark commented on hawkeye-core/src/models.rs
> +            .into_iter()
I don't think this needs to be cloned:

```suggestion
            .iter()
```

2022-01-06 15:57 UTC, jakubclark commented on hawkeye-api/src/filters.rs
> +impl Serialize for ErrorResponse {
Why not just `[derive(Serialize)]`? This impl looks like what the derived impl would look like

2022-01-07 09:08 UTC, LyleScott commented
oops, closed automagically and accidentally from some branch golf I was doing

2022-01-07 23:12 UTC, LyleScott commented on hawkeye-core/src/config.rs
> +        .unwrap_or("jpg,jpeg,png".into())
whoa, thanks for that. I read up on why this would be changed as such and I was unaware of the eager vs lazy semantics of the two. totally get it, now. I imagine i've done this in several places so I'll try to address those in this and other PRs.

2022-01-07 23:13 UTC, LyleScott commented on .gitignore
> +.idea
oh nice, great idea.

2022-01-07 23:20 UTC, LyleScott commented on .gitignore
> +.idea
I see now! that's awesome. i'll just revert this change then.

2022-01-07 23:36 UTC, LyleScott commented on hawkeye-api/src/filters.rs
> +        // state.serialize_field("code", &self.code.as_u16())?;
will remove.

2022-01-07 23:36 UTC, LyleScott commented on hawkeye-api/src/filters.rs
> +        // state.serialize_field("code", &self.code.as_u16())?;
```suggestion
```

2022-01-07 23:38 UTC, LyleScott commented on hawkeye-api/src/filters.rs
> +        message: message.to_string(),
you're right. and now i get to shorten it even more since the key name matches the variable name.

2022-01-07 23:41 UTC, LyleScott commented on hawkeye-worker/src/main.rs
> +    // let detector = SlateDetector::new(&slate::load_img(watcher.slate_url.as_str())?)?;
```suggestion
```

2022-01-07 23:58 UTC, LyleScott commented on hawkeye-core/src/models.rs
> +            }
@rafaelcaricio is that to keep the `Err` lazy?

Readability wise, the 1st is easier for me to instantly grok and understand whereas the 2nd one I have to read through the entire operation and reason about it a bit to figure out what's going on.

2022-01-08 00:03 UTC, LyleScott commented on hawkeye-core/src/models.rs
> +        }
This one in particular needs to be the way it is to allow `slate.is_valid()` to fall through to the transparent return. it returns a `Result<>`. 

I __could__ change it to that `Ok(())` style if I were to make the change:
```diff
- Some(slate) => slate.is_valid(),
+ Some(slate) => return slate.is_valid(),
```

```rust
    pub fn is_valid(&self, state: &VideoMode) -> Result<()> {
        if state == &VideoMode::Slate {
            match &self.slate_context {
                Some(slate) => return slate.is_valid(),
                None => Err(eyre!("A `slate_context` is required for from=Slate")),
            }
        } else {
            Ok(())
        }
    }
```

2022-01-08 00:07 UTC, LyleScott commented on hawkeye-core/src/models.rs
> +                    }),
Yeah, i meant to change those based on an early comment made on another PR. I've changed all instances of `Option::from` to `Some` 👍🏼

2022-01-08 00:18 UTC, LyleScott commented on hawkeye-core/src/models.rs
> +            .into_iter()
great catch, I should have followed up on that one. you're absolutely right about that.

2022-01-08 00:23 UTC, LyleScott commented on hawkeye-api/src/filters.rs
> +impl Serialize for ErrorResponse {
Good question. I think I had tried that and got a lot of complaints from Warp I wasn't doing it right. Let me investigate that further so I can respond 😓  60% chance it's just my n00b mistake

2022-01-08 00:42 UTC, LyleScott commented on hawkeye-api/src/filters.rs
> +impl Serialize for ErrorResponse {
It looks like you're absolutely right. I think it was an artifact of my struggle with implementing `warp` validation bubbling up... it took some iterations to get it right for sure.

2022-01-08 01:09 UTC, LyleScott commented
> First pass on reviewing. Have you ran [`cargo clippy`](https://github.com/rust-lang/rust-clippy) after the changes here?

I did now! I knew I was forgetting something like that.

2022-01-10 12:40 UTC, rafaelcaricio commented on hawkeye-core/src/models.rs
> +            }
> @rafaelcaricio is that to keep the Err lazy?

This is one reason, yes. But if we talk about ergonomic Rust code, people will be using combinators all the time. I agree it takes some time to get used to it, but there are some benefits from using them. The compiler can make some optimizations based on the usage of combinators.

2022-01-11 07:26 UTC, LyleScott commented on hawkeye-worker/src/img_detector.rs
> +            .iter()
I thought about it when I saw that library, but it was too late in the dev cycle. I'll explore this on its own and do a new PR for that if it makes sense.

2022-01-11 23:43 UTC, LyleScott commented on hawkeye-api/src/handlers.rs
> -            return Ok(reply::with_status(
fyi, the rest of this file's changes are due to `clippy` fixes

2022-01-11 23:47 UTC, LyleScott commented on hawkeye-core/src/models.rs
> +            match self.from_context {
I spent some time trying to make this a chain, but I could not quite figure it out in the time allotted and moved on.

2022-01-26 18:16 UTC, rafaelcaricio commented on fixtures/watcher-basic.json
> +      },
I think this is complicating the JSON and the code as consequence. Maybe we could restructure this a little differently.

What about this?
```json
      "from": {
        "frame_type": "content"
      },
      "to": {
        "frame_type": "slate",
        "url": "https://example.com/resources/slate_fixtures/slate-2-cbsaa-213x120.jpg"
      }
```

In Rust this could become:
```rust
#[serde(tag = "frame_type")]
pub enum VideoMode {
    Slate {
        url: String,
    },
    Content,
}
```

Consequently, this also would simplify everywhere else. Like:
```rust
pub struct TransitionStateChange(
    VideoMode,
    VideoMode
);
```

No need for a "SlateContext" struct and everywhere is much cleaner. What do you think?

2022-01-26 20:04 UTC, LyleScott commented on fixtures/watcher-basic.json
> +      },
I originally started down this path, but I've learned to avoid this type of API behavior  for other reasons more generally (ie, beyond this case). I'll try to explain why I favor discriminated contexts.

For example, in this case, overloading `to` and `from` objects to be more polymorphic risks cyclomatic complexity for API consumers and the codebase. A flat payload becomes quite dynamic due to "transparent" dependencies that make it hard to tell what fields are related to another field when you read the payload, _especially_ after having several fields. You could argue the same about code implementation;  you no longer have a constant way to refer to the data you are after, but instead rely on mapping or undocumented tribal knowledge on how things fit together. To minimize this logic leap, one field, the discriminator, is the kicker to open up another concrete object compared to an adhoc transparent grouping on the same object. I've seen too many payload base don a flat structure that end up being an illogical mess.

IMHO, this discriminator is a powerful tool to help the User avoid understanding extra intricacies of the API, helps the mental model be clear, and gives the code a direct place to get the info instead of piecing all the conjoined bits via some map. 

So, given the two variants:

```json
{
    "from": {
        "frame_type":  "slate",
        "slate_url": "http://....",
        "bbox": {"origin": [1,2], "w": 123, "h", 456, ...},
    }
}
```

```json
{
    "from": {
        "frame_type":  "slate",
        "slate_context": {
            "slate_url": "http://....",
            "bbox": {"origin": [1,2], "w": 123, "h", 456, ...},
        }
    }
}
```

I do like the `frame_type` idea being in the `from` object. having them separate felt awkward and I couldn't put my finger on it.

Keeping it completely flat worries me in regards to scaling the payload as we add features, though. If we have other `frame_type`s that need their own data, for example.

2022-01-26 20:48 UTC, LyleScott commented on fixtures/watcher-basic.json
> +      },
With regards to the rust code being cleaner, I do enjoy the cleanliness of your proposed solution above much better. I might be able to do better knowing a whole lot more than when I wrote this, but it did seem annoying and unnecessary passing multiple pieces of info around instead of a clean `VideoMode`. I can try to give it another look to see if we can have a payload that is nice to the user, but also make the implementation cleaner.

2022-01-27 03:32 UTC, LyleScott commented on fixtures/watcher-basic.json
> +      },
I think I got what I'm after. I managed to use `serde` to make the payload use a discriminated type, but it serializes to a Rust Enum that can be used just like old times (and like you suggest). 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=008db18f1d5a37a6d2ad4c5898da73bd

2022-01-27 03:40 UTC, LyleScott commented on fixtures/watcher-basic.json
> +      },
@rafaelcaricio let me know if you agree with this approach. i dig it since it will simplify the code and what I was originally chasing. this is a bigger refactor, so I didn't want to do too much without agreement.

2022-01-27 14:59 UTC, rafaelcaricio commented on fixtures/watcher-basic.json
> +      },
@LyleScott Hey, I like this idea! I had a look at the code snippet you shared here and as long as the "content" frame type does not need to have any data the code can be simplified greatly to produce the same results. Please have a look here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=17953171b8f1ac18bc507983c1a6d61d

Anyway, I think we have a way forward! 🥳

2022-01-27 17:17 UTC, LyleScott commented on fixtures/watcher-basic.json
> +      },
whoa, nice! I looked at a ton of serde docs yesterday and didn't come across that one. you're serde foo is strong!

2022-01-27 17:54 UTC, rafaelcaricio commented on fixtures/watcher-basic.json
> +      },
Google pointed me to this https://serde.rs/enum-representations.html 😅

2022-01-31 16:57 UTC, LyleScott commented on README.md
> +> data.
```suggestion
> Data is persisted via Kubernetes metadata. For example, IDs of created objects may be represented in a Kubernetes resource's `metadata` key/value pairs. This value can later be filtered on when we are looking for specific resources or a "list view" can easily be built much like doing a `select * from some_kinda_resource` in a RDMS. The Hawkeye API couriers data between JSON and and Kubernetes resources using this pattern.
```

2022-01-31 16:57 UTC, LyleScott commented on fixtures/watcher-basic.json
> +      },
This is all sorted.

2022-01-31 16:58 UTC, LyleScott commented on hawkeye-core/src/config.rs
> +    pub static ref SLATE_URL_FILE_EXTENSIONS: Vec<String> = std::env::var(SLATE_URL_FILE_EXTS_ENV)
Yeah, that's true. I've made constant.

2022-02-08 17:59 UTC, rafaelcaricio commented on hawkeye-core/src/config.rs
> +    #[derive(PartialEq)]
Do we need this derive here? Interesting.... 🤔

2022-02-08 17:59 UTC, rafaelcaricio commented on hawkeye-worker/src/actions.rs
> +// TODO: ^^^ why?
I think it is because this type is only making things more complicated in the code. We would be better without it.

2022-02-08 17:59 UTC, rafaelcaricio commented on hawkeye-worker/src/video_stream.rs
> +    // TODO: Comment on why this is needed.
This is just for debugging. I would like to know if there were results from the `frame_source` iterator without any frames.

2022-02-15 15:59 UTC, LyleScott commented on hawkeye-core/src/config.rs
> +    #[derive(PartialEq)]
I remember adding this due to a compiler warning, but I'd have to check again.

2022-02-17 08:03 UTC, LyleScott commented on hawkeye-api/Cargo.toml
> +warp = { version = "0.3", default-features = false, features = ["tls"] }
honestly, I just left it in to be safe at the time. I think you're right about it not being true e2e ssl.

2022-02-17 08:04 UTC, LyleScott commented on hawkeye-api/Cargo.toml
> +warp = { version = "0.3", default-features = false, features = ["tls"] }
```suggestion
warp = { version = "0.3", default-features = false }
```

2022-02-17 08:09 UTC, LyleScott commented on hawkeye-worker/src/video_stream.rs
> +    // TODO: Comment on why this is needed.
```suggestion
    // TODO: This is just for debugging and to know if there were results from the
    // frame_source iterator without any frames.
```

2022-02-17 08:10 UTC, LyleScott commented on hawkeye-core/src/config.rs
> +    #[derive(PartialEq)]
nah, not needed anymore. that logic must have gone away.

2022-02-17 08:11 UTC, LyleScott commented on hawkeye-worker/src/actions.rs
> +// TODO: ^^^ why?
cool, thanks! commented on this in the code.

2022-02-23 13:22 UTC, rafaelcaricio approved these changes
LGTM

2022-03-01 02:48 UTC, merged