Sentry
cbsinteractive/hawkeye pull request #51
Opened 2022-01-07 21:32 UTC by LyleScott

Implements sentry to report on panics and `log::error!("...")` messages.

closes #33

2022-01-10 12:35 UTC, rafaelcaricio requested changes
@LyleScott I don't know if you have [`clippy`](https://github.com/rust-lang/rust-clippy) installed, but I would suggest running it before opening PRs. It has a lot of very good linting suggestions and is a great tool to learn from the suggestions.

2022-01-10 12:35 UTC, rafaelcaricio commented on hawkeye-core/src/utils.rs
> +            environment: Some(Cow::from(config::HAWKEYE_ENV.to_string())),
The idea of them using `Cow` is to avoid creating unnecessary strings. Here I would suggest to use `.as_str()` instead of allocating a new `String` from `HAWKEYE_ENV` which is already a `String`.

```suggestion
            environment: Some(Cow::from(config::HAWKEYE_ENV.as_str())),
```

2022-01-10 12:35 UTC, rafaelcaricio commented on hawkeye-core/src/utils.rs
> +        config::SENTRY_DSN.to_string(),
There is an implementation of `impl<'a> IntoDsn for &'a str` in Sentry lib code. So we also don't need to allocate a new string here.

2022-01-11 06:55 UTC, LyleScott commented on hawkeye-core/src/config.rs
> +    pub static ref HAWKEYE_ENV: String = std::env::var(HAWKEYE_ENV_ENV).unwrap_or("local".into());
oops, old copy pasta

2022-01-11 06:59 UTC, LyleScott commented on hawkeye-core/src/utils.rs
> +        config::SENTRY_DSN.to_string(),
totally missed it, thanks. fixed

2022-01-11 07:03 UTC, LyleScott commented on hawkeye-core/src/utils.rs
> +        config::SENTRY_DSN.to_string(),
i just need to start reviewing all lines I added with `.to_string`...

2022-01-11 11:21 UTC, rafaelcaricio commented on hawkeye-core/src/config.rs
> +    pub static ref SENTRY_DSN: String = std::env::var(SENTRY_DSN_ENV).unwrap_or("".into());
Missed this one too
```suggestion
    pub static ref SENTRY_DSN: String = std::env::var(SENTRY_DSN_ENV).unwrap_or_else(|_| "".into());
```

2022-01-11 21:59 UTC, LyleScott commented
`clippy` was ran, but it picked up stuff outside the scope of this feature and that I've already fixed in the multislate branch.

2022-01-11 23:24 UTC, LyleScott commented
I reworked this slightly to use a `SENTRY_ENABLED` flag and added some tests.

2022-01-14 10:42 UTC, rafaelcaricio commented on hawkeye-core/src/utils.rs
> +    use crate::utils;
Just FYI... you can also do:
```suggestion
    use super::*;
```

2022-01-14 10:43 UTC, rafaelcaricio approved these changes

2022-01-14 18:35 UTC, merged