Add user/password auth
cbsinteractive/hawkeye pull request #54
Opened 2022-02-18 17:38 UTC by LyleScott

There's a lot of ways to take this story, so feedback welcome. 

Basically, added new endpoints that do what you'd expect.

```shell
GET       /users
POST      /users
GET       /users/<id>
PUT       /users/<id>
DEL       /users/<id>
POST      /auth/login
```

A User has fields:

```rust
pub struct User {
    pub id: Option<String>,
    #[serde(serialize_with = "k8s_label_datetime_to_iso8601")]
    pub created_at: Option<String>,
    #[serde(serialize_with = "k8s_label_datetime_to_iso8601")]
    pub updated_at: Option<String>,
    pub username: String,
    #[serde(skip_serializing)]
    pub password: Option<String>,
    pub password_hash: Option<String>,
    pub role: UserRole,
}
```

Auth Workflow: https://github.com/LyleScott/hawkeye/tree/users_crud_with_jwt#authentication

You create seed users via a cli: https://github.com/LyleScott/hawkeye/tree/users_crud_with_jwt#seed-admin-user

More words at: https://github.com/LyleScott/hawkeye/tree/users_crud_with_jwt

Postman has been updated.

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/1007900/154733962-f5d099fd-fb3d-46f5-9b36-b9960346fb45.png">

2022-02-18 18:49 UTC, LyleScott commented on hawkeye-worker/Cargo.toml
> +edition = "2021"
thought i'd slip this in :D

2022-02-18 19:14 UTC, dudymas commented on README.md
> +cargo run --bin hawkeye-api create-user --help
shouldn't this use the -- separator to make sure the --help doesn't reach cargo?
```suggestion
cargo run --bin hawkeye-api -- create-user --help
```

2022-02-18 19:58 UTC, LyleScott commented on README.md
> +cargo run --bin hawkeye-api create-user --help
@dudymas In this particular case, it's fine since it is a subcommand.

It is indeed needed for the general `--help`, though. I should mention that in the docs. 

```
cargo run --bin hawkeye-api -- --help
```

2022-02-18 22:52 UTC, LyleScott commented on hawkeye-api/src/templates.rs
> +                "hawkeye.api.user.owner_id": owner_id.clone().unwrap_or_else(|| "".to_owned()),
This introduces some namespacing i've created in the "metadata tagging" branch/task.

2022-02-23 13:30 UTC, rafaelcaricio commented on api.Dockerfile
> +ENTRYPOINT ["/hawkeye-api start-api"]
Interesting, I thought it was necessary to be like:
```suggestion
ENTRYPOINT ["/hawkeye-api", "start-api"]
```

Does this current way also worked?

2022-02-28 13:20 UTC, jakubclark requested changes

2022-02-28 13:20 UTC, jakubclark commented on hawkeye-api/src/backend.rs
> +                .collect::<Vec<User>>())
If possible, it would be nice to implement the trait `From<&Secret> for User`, but that doesn't seem possible since `Secret` is from the k8s library, which is not part of `hawkeye-core`. That would simplify the body of the`list_users` significantly. 

I still think it's worth extracting the logic of converting a `&Secret` to a `User` into a dedicated function, at least. Similar to `user_to_secret()` below.

The creating the Vec<User> would simply be:

```rust
let users: Vec<User> = secrets.items().iter().map(extract_user).collect();
```

2022-02-28 13:20 UTC, jakubclark commented on hawkeye-api/src/backend.rs
> +                    "hawkeye.api.user.id".to_string(),
I suggest storing all these label names (hawkeye.api.user.id, hawkeye.api.user.role, etc.) as top-level constants, to be re-used in other places:

```rust
const API_USER_ID_KEY: &str = "hawkeye.api.user.id";
```

2022-02-28 13:20 UTC, jakubclark commented on hawkeye-api/src/backend.rs
> +pub async fn create_user(user: &mut User, k8s_client: &kube::Client) -> Result<User, Report> {
I think it would be better to accept a `User` here, and return it at the end as well:

```suggestion
pub async fn create_user(user: User, k8s_client: &kube::Client) -> Result<User, Report> {
```

2022-02-28 13:20 UTC, jakubclark commented on hawkeye-api/src/backend.rs
> +        .map(|secret| {
Same here, a dedicated function to convert a `Secret` to a `User` would be nice

2022-02-28 13:20 UTC, jakubclark commented on hawkeye-api/src/backend.rs
> +            .find(|&secret| {
Same here, a dedicated function to convert a `Secret` to a `User` would be nice

2022-02-28 13:20 UTC, jakubclark commented on hawkeye-api/src/backend.rs
> +    // })
Leftover code?

2022-02-28 13:20 UTC, jakubclark commented on hawkeye-api/src/backend.rs
> +}
Leftover code?

2022-02-28 13:20 UTC, jakubclark commented on hawkeye-api/src/filters.rs
> +/// PUT /v1/users/<id>
```suggestion
/// GET /v1/users/<id>
```

2022-03-15 23:57 UTC, LyleScott commented on hawkeye-api/src/auth.rs
> +async fn authorize(
I agreed and tried to change it, but `warp` actually needs it to be a future.

2022-03-15 23:58 UTC, LyleScott commented on hawkeye-api/src/auth.rs
> +                    && jwt_token_role != UserRole::Admin)
No contest there. Good idea.

2022-03-16 00:05 UTC, LyleScott commented on hawkeye-api/src/auth.rs
> +                role: UserRole::Admin,
arrrg. needs more unit tests. that was buried in there. 

```suggestion
                role: authorized_role,
```

2022-03-16 05:08 UTC, LyleScott commented
Sorry, y'all. I had some cleanup to do, clearly.

I'm also going to merge in the story to make Watchers editable. And i'll make that upstream until it's merged to `master`. There's a lot of merge conflicts since both branches added arguments to the same functions, so I'm just biting the bullet since this JWT branch will make it in _after_ edit support. Please stand by why I do that.

2022-03-24 20:41 UTC, LyleScott commented
> Hey @LyleScott, wouldn't it make more sense to implement in Hawkeye a generic auth layer that integrates with a 3rd-party JWT provider? In Hawkeye we would just check if the JWT matches a public key?

I mean, i guess that's a way it could go. I might as well stop wasting my time on this if that's what people want instead, though. I'll stop work on this until I hear back.

2022-04-01 15:20 UTC, closed without merging